import { NextPage } from "next";
import { useSession } from "next-auth/react";
import Head from "next/head";
import Link from "next/link";

const Dashboard: NextPage = () => {
  const { data: sessionData, status } = useSession();
  console.log(sessionData, status);
  return (
    <>
      <Head>
        <title>LIYPE Dashboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center py-2 dark:text-white">
        <h1 className="text-6xl font-bold">Dashboard</h1>
        {status === "loading" ? (
          <div className="block w-full justify-center">
            <div className="h-32 w-32 animate-spin rounded-full border-b-2 border-gray-900"></div>
          </div>
        ) : (
          <div className="flex flex-col items-center justify-center">
            {status === "unauthenticated" ? (
              <Link
                href="/dashboard/signin"
                className="rounded-lg bg-blue-500 p-4 text-white"
              >
                Iniciar sesión
              </Link>
            ) : (
              <>
                <h2 className="text-2xl font-bold">
                  {sessionData?.user?.name}
                </h2>
                <p className="text-xl">{sessionData?.user?.email}</p>
              </>
            )}
          </div>
        )}
      </main>
    </>
  );
};

export default Dashboard;
